# Generated by Django 4.0.3 on 2022-03-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
