# Generated by Django 4.0.3 on 2022-03-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='alien.jpg', null=True, upload_to=''),
        ),
    ]
